name: Test  Continues and Integration

on:
  push: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkoutv@2
      - name: Setup Node Dependencies
      - run: cd ./client/
      - run: npm install
      - name: Start serverless application
      - run: npm start
      - wait-on: "http://localhost:3000"
      - wait-on-timeout: 120
